### PR TITLE
Added LIBXML_NOCDATA

### PR DESCRIPTION
**Pull request by hor-net**
When saving the HTML result inlined javascript is wrapped with CDATA, simply adding LIBXML_NOCDATA do the DomDocument loadHtml fixes this

### CODE REVIEW

**Comment by solleer** [comment]
Isn't this already fixed?

**Comment by solleer** [comment]
#144

**Comment by hor-net** [comment]
Nope here is missing in the master branch

https://github.com/Level-2/Transphporm/blob/master/src/Template.php

**Comment by TomBZombie** [comment]
Unfortunately NOCDATA is ignored, but the fix in #144 does solve this. If not, can you provide some test code that triggers the problem?

**Comment by hor-net** [comment]
Well it seems to do the trick in my test environment:

$ php -v
PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) (
NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1-1+deb.sury.org~xenial+1, Copyright (c)
1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

I'm writing a wordpress theming framework and i want to use Transphporm
to provide the ability to theme creators to use a mix of html files and
configs files to create complete wordpress themes (including custom post
type support) without php knowledge and the failing code is the
javascript generated by the wp_head() wordpress call.

adding the LIBXML_NOCDATA removes the CDATA wrapping around it and
eliminates javascript errors.

If you found that it's being ignored in your tests it's probably due to
some PHP version strangeness, it would not be the first time i see them,
which version you tested it against?

Saverio Vigni

**Comment by TomBZombie** [comment]
Here's a demo script: https://3v4l.org/2M9mO

The trick to solving this was using saveHTML() rather than saveXML() which never includes cdata. Xml isn't affected: https://3v4l.org/5gjLa 

Do you have a sample script where CDATA is added incorrectly?

**Comment by hor-net** [comment]
Well my case is a little different since the content of what's in <head>
is being replaced by a TSS rule and the content is being generated by
the wp_head(); wordpress api

the CDATA appears on the content replaced by the TSS rule and coming
from my "data" array.

The funny thing now is that i'm trying to reproduce the issue (after
reverting my changes to the GIT copy i have here) and now it seems like
it's working fine...I'm not using any kind of caching so i don't
understand what is happening... I'll try again later and see if I can
reproduce it.

Saverio

**Comment by cxj** [comment]
Here is an idea that might help you.

I've seen CDATA wrappers on my Javascript as well -- but it was all my own error.  It's very subtle.  The problem is XML has different entities which must be encoded versus HTML, and also has different rules for attributes.  Specifically what tripped me up is this:
```xml
<a href="#" data-modal>
```
Which is _not_ valid XML, but it _is_ valid HTML.  The correct XML is this:
```xml
<a href="#" data-modal="">
```
Note the empty string as a value for the attribute `data-modal`.

Perhaps something similar is causing your problem?

**Comment by solleer** [comment]
Can this be closed?

**Comment by solleer** [comment]
Is there still a reason for this?

**Comment by hor-net** [comment]
Hi i've left the project aside for the moment but as far as i remember it's somehow working so you can close this.
Thank you
Saverio

**Pull request closed without merging**
