### PR TITLE
fixed capital letters and date format

### PR DESCRIPTION
**Pull request by hobbeshunter**
Also added "day_before_yesterday" and "day_after_tomorrow" as we use it quite often in German.

### CODE REVIEW

**Comment by smolinari** [comment]
I created the German locale file. :smile: 

If you look at the English locale file, those terms you changed are capitalized, so I was assuming they are at the beginning of the phrase they would be used for (or they stand alone), so they would also need to be capitalized in German too. 

With "day_before_yesterday" and "day_after_tomorrow", nice of you to add them, but if there is no date format calculation for those time frames, so they will never be used. In other words, if @TomBZombie  (or you or someone else) doesn't add the terms in the enEN file *along* with the necessary date format calculations in Transphporm, then those added terms are superfluous.

Scott

**Comment by TomBZombie** [comment]
I'll add the calculation for those times. For capitalisation, perhaps it should be lowercase and we offer a ucfirst formatter as well so you'd use `format: relative, ucfirst` to uppercase the first letter when you want to.

**Comment by smolinari** [comment]
More flexibility is almost always a good thing!

Scott

**Comment by hobbeshunter** [comment]
Hi Scott,

didn't had a look into the english file, just thought that this isn't quite correct so, as you can't make any assumptations about where it'll be used. And yeah I knew that there weren't any functions for "day_before_yesterday" and "day_after_tomorrow". I just wanted to add them as I thought it would nice to have them.
Cheers,
Martin

**Pull request merged**
