### PR TITLE
Added enUS Locale

### PR DESCRIPTION
**Pull request by solleer**

### CODE REVIEW

**Comment by TomBZombie** [comment]
We'll probably need different locales for different timezones, or some way of having different timezones in a single locale but this is a good start.

**Comment by smolinari** [comment]
Time zones aren't really a part of locales, are they?

Scott

**Comment by solleer** [comment]
They have a timezone section that Transphporm uses when formatting dates

**Comment by smolinari** [comment]
What formatting does a time zone do? It is just an offset needed to correctly format the user's view of time values, not the formatting of them. I'd take time zones out completely. It is a totally different piece of data, specific to each user. 

Scott

**Pull request merged**
