### PR TITLE
Not pseudo now parses the css

### PR DESCRIPTION
**Pull request by solleer**
This allows calls to data in the not pseudo

### CODE REVIEW

**Comment by TomBZombie** [comment]
What is the benefit of this?  `:not()` takes a CSS selector like `:not(.two)` or `:not(p)` to select an element. When would `:not(data())` be useful?

**Comment by solleer** [comment]
```
#messages > div { repeat: data(); }
#messages > div:attr(class) { content: iteration(type); }
#messages > div span.message { content: iteration(message); }
#messages > div i:not("." + iteration(type)) { display: none; }
```

**Comment by TomBZombie** [comment]
ah, makes sense.

**Comment by solleer** [comment]
My direct changes will not work with the new updates though

**Comment by TomBZombie** [comment]
How did this work?

`.two` would be parsed to `two` and break. I'd rather not force `:not(".two")` although semantically it makes sense, it doesn't follow CSS's standard.

**Comment by TomBZombie** [comment]
Ok I've fixed this. When `.` is not preceded by anything it's treated as part of the next string so `foo.bar` is treated as looking up `bar` in `foo` whereas .foo is treated as the string ".foo"

It's a bit of a hack but it should be ok. There's no reason you'd ever want `.` at the start of an expression and have it act as traversal.

**Pull request closed without merging**
