### PR TITLE
Pseudo matcher updates

### LINKED ISSUE #114: Pseudo Matcher Update
I think the pseudo matcher could use an update. It should parse the pseudo into tokens before passing it.

- [x] Parse the pseudo into tokens before passing it

Possible other updates:
- [x] Have the match function pass args

Earlier possible things that are canceled
* Have `getFuncArgs` require an element (this is not necessary because `PropertyHook` sets the element)
* Have the pseudo matcher parse the string? (Don't know how this would be done well since it would read things like `not()` as a function) This is not necessary with the new format of the match function in the interface

I thing the best way is to have the match function in the pseudo interface become
```php
public function match($name, $args, \DomElement $element)
```
It would get args by using its own function `getFuncArgs` which will be updated to parse the tokens

Also @TomBZombie, can you merge some of the PR's. The PR with root path allowance for things like template can be canceled if the baseDir changes with each file like we talked about in #112 because right now it is my primary workaround to allow templates from imported files.
Merging all the PR's would help because then I have a central copy to work off of since there are lots of pull requests. Don't merge #110 though since I am having some issues because of it.
This updating of the pseudo matcher is a step in #91 and will help with using functions everywhere (#102).
Please discuss this.

### PR DESCRIPTION
**Pull request by solleer**
This is the pull request for everything discussed in #114 and resolves #114. Not everything has been added yet. Check #114 for the check list. Currently it has been switched to using tokens.

### CODE REVIEW

**Comment by solleer** [comment]
The pseudo matcher now parses tokens.
The main problem that was already present before the update is if you have something like
```css
p:not(div.two p) {content: "foo"; }
```
That will not match but this will
```css
p:not("div.two p") {content: "foo"; }
```

**Comment by solleer** [comment]
There is no way to fix this reasonably. It is too difficult to try to detect whether tokens need to be parsed so to fit most use cases it is better to always parse it. It also isn't that hard for someone to add quotes around the selector.

**Comment by solleer** [comment]
# About Content Values Fix
Problem: Sometimes the `values` array was multidimensional and other times not
Scenarios:
- The template function was used (the function returns an array of nodes)
- The nl2br format was used (same reason as above)
Fix: The `getNodes` generator now calls itself if it is an index is an array (it works very well since it uses yield like it already did so it can handle any depth of array)

**Comment by solleer** [comment]
This branch is ready to merge but until it is merged I will probably keep adding stuff

**Comment by TomBZombie** [comment]
I'll have to manually merge the rest of these PRs as there seems to be some conflicts. I've been away for the last week without any internet access, great work! :)

**Comment by solleer** [comment]
Thanks, Once this is merged I will work on having sheet use the tokenizer.

**Comment by solleer** [comment]
I am working on sheet using the tokenizer and am making good progress. Can this be merged so I can easily open a PR to discuss my changes in sheet.

**Comment by solleer** [comment]
The problem I have left is that when the csstoxpath accepts tokens then it doesn't know the difference between when the original string was `div .foo` vs `div.foo`

**Comment by TomBZombie** [comment]
Yes, I started working on this and reverted it, the tokenizer needs to supply a whitespace token, which needs ignoring elsewhere. I'll have to merge this PR manually as it's got some conflicts

**Pull request merged**
