### PR TITLE
Tokenizer Used Everywhere

### PR DESCRIPTION
**Pull request by solleer**
First I am going to have CssToXpath accept tokens.

### CODE REVIEW

**Comment by solleer** [comment]
@TomBZombie I am currently trying to get Tokenizer to parse Whitespace. Everything I have tried doesn't pass. I am running out of memory and I don't know why.

**Comment by solleer** [comment]
The tests just freeze when I add one if statement to value parser
```
if ($token['type'] === Tokenizer::WHITESPACE) continue;
```

**Comment by TomBZombie** [comment]
I've just merged this so I can tests with what you have, you also now have write access to this repo so you should be able to merge PRs yourself :)

**Comment by solleer** [comment]
I had it as a PR just so I could keep track of it better

**Comment by TomBZombie** [comment]
what did you change in the tokenizer class? You'd need to add `Tokenizer::WHITESPACE` to the `doSimpleTokens` function

**Comment by solleer** [comment]
That is what I did

**Comment by solleer** [comment]
I hadn't commited it

**Comment by TomBZombie** [comment]
The test that is causing the infinite loop is `testNestedData` but that's also the most complex test so doesn't help much. I'm trying to find the while loop that causes it but I can't get xdebug working at the moment.

**Comment by TomBZombie** [comment]
I've fixed it but I'm not sure why. Changing `getProperties` in sheet to filter out whitespace solves it:

```php
	private function getProperties($str) {
		$tokenizer = new Tokenizer($str);
		$tokens = $tokenizer->getTokens();

		$rules = [];
		$i = 0;
		foreach ($tokens as $token) {
			if ($token['type'] === Tokenizer::SEMI_COLON) $i++;
			else if ($token['type'] !== Tokenizer::WHITESPACE) $rules[$i][] = $token;
		}

		$return = [];
		foreach ($rules as $rule) {
			if ($rule[1]['type'] === Tokenizer::COLON) $return[$rule[0]['value']] = array_slice($rule, 2);
		}

		return $return;
	}
```

However, I might try to fix it higher up as that's a workaround more than a fix. Then again, we're already looping through all the tokens at that point so perhaps it's the best place for it.

**Comment by TomBZombie** [comment]
I'm going to change the `parse` function in sheet to also use Tokenizer.

**Comment by TomBZombie** [comment]
Actually this fix won't work, it will prevent us allowing properties like `name: foo bar` as it will be converted to `name: foobar`

**Comment by solleer** [comment]
That is so confusing how it loops at value but not at sheet

**Comment by solleer** [comment]
I did the change and all tests still pass. It never passed whitespace as a token before so removing it will not affect anything.

**Pull request merged**
