### PR TITLE
Update locale translation files

### PR DESCRIPTION
**Pull request by tontof**
Using your comment https://github.com/Level-2/Transphporm/pull/21#issuecomment-154705332 I've updated locales.

In the future, I think you will have to modify the way you manage pluralization as some languages have several plural for words:
- https://github.com/czukowski/I18n_Plural#example-2
- https://github.com/czukowski/I18n_Plural#example-3

And the definition of plural is quite complicated: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

Using one, few, many, other is the simple way, but the more flexible is using a number that help to decide which translation to use:
- http://symfony.com/doc/current/components/translation/usage.html#explicit-interval-pluralization

Some inspiration can be found here: http://i18next.com/pages/doc_features.html (search simple plural, indefinite plural, multiple plural forms for interesting parts)

### CODE REVIEW

**Comment by smolinari** [comment]
A note on translations in general: although translations aren't a direct responsibility of a template system, the language offered in the application text needs to be considered and be "switchable" and be passed through the template system.  This means translations can come greatly into play with the caching of templates. I believe Symfony processes translations at runtime. In other words, if the system is multilingual, Symfony pulls in the required translated text for each request, even though templates are cached. So, no caching of translated values, which to me a total waste of processing, since application translations don't really change all that much, once they are set. (we are not talking about translations of stored content, but rather, only about stored application terminology/ phrases.)

I believe the cache system you are currently working on Tom will be storing final results of Transphporm's template compilation. If true, then the language of terms and phrases will also need to be accounted for and thus, each compiled template/ page (not sure what is being cached) will need its own translated version. I am not sure why Symfony didn't go that route either. All suggestions to move in that same direction, in order to make the template output even more performant, have been ignored too.  

The fact that text can be translated also means I think we need to offer a standard formatter, which requires a user's language choice, a phrase name, and any other attributes (like the number of items suggested by tontof). 

You might be asking, why the user's language choice AND not the locale? Because, a user might be in Germany, and want numbers, currency and time values formatted according to the German locale, but want the language of all the application text to be in English. So, locale should only be formatting numbers, currency and datetime values. Any terms or phrases should be part of a translation system. 

Currently, Transphporm's locale formatter is mixing these concerns and thus, we'd have a problem, if someone insisted the system works as I just suggested above. So, I suggest removing the terms altogether in the locale files and leaving such "rephrasing" of datetime values up to the translation formatter. That way, you can avoid having to make any decisions on how things are translated at all with locale formatting, as translations should actually be completely outside the scope of Transphporm. Transphorm only needs to offer a 

1a.  simple and global way to format text to a different language through a custom "translation" formatter

suggestion: a new form of `data()`. like 

`main {content: textdata(welcome-text));}`

2. cache the output in different languages, or inject translations at runtime. Although, I don't think that is smart.

Scott

**Comment by smolinari** [comment]
Actually, let's detail this a bit more.

Text with no added variables (like a number).

`main {content: textdata(welcome-text));}`

Text with a single variable.

`strikes-warning {content: textdata(strikes-warning, count));}`

Text with multiple variables.

`current-time {content: textdata(all-times-are-gmt-x-time-now-is-y, users-tz-in-hours-from-gmt, time-now); data(time-now); format: time;}

The last one would be a template that is never cached obviously. :smile:

Is this making any sense? 

Scott

**Comment by smolinari** [comment]
Actually, scratch all that! :smile:

Maybe it could be done like this? 

`current-time {content: translate(data(time)); format: time;}`

And `time` comes from something like

```
$data = ['time' => [
   'phrase' => 'all-times-are-gmt-x-time-now-is-y',
   'user-offset' => '+2',
   'time' => '2015-12-22 14:34'
];

// All times are GMT + 2. The current time now is 2:34 p.m.
```

Scott

**Comment by TomBZombie** [comment]
Interesting, yes I think we will have to change the way it works at some point, alternatively we could offer alternative formatters that support a wider range of locales (as well as different calendars) but that's not going to be a huge priority.

**Comment by TomBZombie** [comment]
For actual localisation, I think it's an application level problem, not really one of the display logic and the "correct" text should be supplied by the application as data. It would be easy enough to build a reusable TSS to handle it. For example:


```css
.i8n {bind: data(translations); content: data(attr(data-string); }
```

```html

<p><span class="i8n" data-string="welcome">Welcome message</span></p>
```

Then you supply the data array with the translations:

```php
$data = ['translations' => 
    [
        'welcome' => 'Welcome back'
    ]
];
```

This requires no extra development for Transphporm and puts any kind of decision making about "What translation should be used?" into the hands of the application developer, where it should be. As you highlighted, you might want German locale but english text. This is an application level concern, not a templating one.

We may need to add an sprintf type formatter to allow this:

```php
.i8n { content: data(attr('data-string)); format: sprintf data(name); }
```

**Comment by smolinari** [comment]
> For actual localisation, I think it's an application level problem, not really one of the display logic and the "correct" text should be supplied by the application as data. 

We could argue about this. The language is a formatting of text output in the display, so one could say it is display logic. The program doesn't know and doesn't care about the text in the output. Now, the content that is dynamic, that is something the display logic shouldn't care too much about. And then there is the static text mixed with dynamic output. That is even more tricky.

I have to refer back to Twig.

http://symfony.com/doc/current/book/translation.html#book-translation-tags
http://twig.sensiolabs.org/doc/extensions/i18n.html

Scott

**Pull request merged**
